### ISSUE TITLE
Customize the text

### ISSUE THREAD

**Issue by coin-au-carre** [abhinav/goldmark-anchor#60]
Is it possible to have more customization on the 
```
Texter:   anchor.Text("#"),
```
I would like it to not be underlined is that possible ?

**Comment by abhinav** [comment]
Hey, @coin-au-carre. goldmark-anchor does not generate an underline for the anchor.
It just generates an HTML `<a>` tag. The styling for your website may be underlining links by default.
Example of generated HTML:

```
<a class="anchor" href="#foo">
```

You can probably use the anchor class to disable underlining of those links.

**Comment by coin-au-carre** [comment]
Wonderful thank you ! using Tailwind I came with this solution

```
<article class="prose lg:max-w-none prose-neutral [&_a.anchor]:no-underline [&_a.anchor]:opacity-40 [&_a.anchor]:transition-opacity hover:[&_a.anchor]:opacity-80">
```
